### ISSUE TITLE
ios video problem

### ISSUE THREAD

**Issue by SunnyVZ777** [because-why-not/awrtc_browser#1]
in the begining, i was using iOS 12. the video simply didn't loaded after the connection is done. after i update it to 12.2, it can display the video panel, but it only play if i press the play button, and it only play in fullscreen mode

**Comment by devluz** [comment]
Safari isn't properly supported yet. Only with iOS 12.2 safari has become compatible to the other browsers to a point that it is worth looking into it. Before that it didn't support VP8/VP9 which are the only freely available video codecs. 

The play button on the video might appear if you have autostart=true in the browser URL. I will remove this in the future as browsers started to block this stop pages from automatically replaying video. Safari might also wrongly trigger this on other situations. 

Before I investigate further could you please describe the exact steps that lead to the problems? Which platforms / browsers and their versions are involved in the process? Which examples did you use?
