### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by tomkis** [because-why-not/awrtc_browser#2]
Hello, any chance we could get this on NPM? 

The module is pretty well prepared already.

**Comment by devluz** [comment]
Not sure if this makes sense on npm given that it is tied to other software outside of npm. There is also another npm module called "awrtc" that is something different

**Comment by devluz** [comment]
I just noticed you already published it on npm yourself. Is there a way I can take control over the npm module later on?

**Comment by tomkis** [comment]
@devluz Ownership transferred to you.
