### ISSUE TITLE
Stopping and starting a call resumes the stream but does not open a video box

### ISSUE THREAD

**Issue by cosmo-naut** [because-why-not/awrtc_browser#3]
What happens:
When I am in a webrtc call and click start/stop it ends the stream. 
If I start the stream again and reconnect by clicking start without refreshing it connects back to the video call but my own webcam doesnt pop up again

**Comment by devluz** [comment]
Which application? The callapp example? So far this is just a testpage to show an actual running example of the ICall API. It isn't designed like a user-friendly application that is ready to use. I can have a look into it next week though

**Comment by cosmo-naut** [comment]
One end is the javascript you hosted and linked to from your website
Other end is me running the SimpleCall.cs method I've added a few things to
My solution is to get the webcam back, I just need to refresh the page.
It's not entirely a huge issue, as it's just my self-facing cam and it still streams and shows up on the other end just fine.

**Comment by devluz** [comment]
It should be fixed with the latest commit. In the end it would be best if you write your own app based on the ICall API and not use the examples directly. The API is kept stable over years but the examples might change any time.
